[package]
name = "os"
version = "0.1.0"
edition = "2021"
authors = ["Orchard Du <orcharddu@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[profile.release]
debug = true

[dependencies]